### ISSUE TITLE
NWS warning information failing

### ISSUE THREAD

**Issue by jcla490** [washington-dnr-fire/wa-fire-dashboard#38]
Unable to pull up the warning text, for example: 
https://alerts-v2.weather.gov/products/NWS-IDP-PROD-4217603-3561709

**Comment by jcla490** [comment]
this is occurring at the source level. I have put in a ticket to the NWS GIS section, owners of this web service.

**Comment by kirk5davis** [comment]
> this is occurring at the source level. I have put in a ticket to the NWS GIS section, owners of this web service.

You sure it's not just a URL change?

**Comment by jcla490** [comment]
it's broken on their own page *shrug*

**Comment by jcla490** [comment]
http://www.arcgis.com/home/webmap/viewer.html?url=http%3A%2F%2Fidpgis.ncep.noaa.gov%2Farcgis%2Frest%2Fservices%2FNWS_Forecasts_Guidance_Warnings%2Fwatch_warn_adv%2FMapServer&source=sd

**Comment by kirk5davis** [comment]
I think I figured this out:

The URL did change! Check it out:

**https://api.weather.gov/alerts/NWS-IDP-PROD-4245300-3580461**  

That first bit is the most important:  https://api.weather.gov/alerts 

That returns straight JSON - we might actually think about popping open a page in our app and styling the message with the properties in the JSON.

**Comment by kirk5davis** [comment]
Never Mind the comment above - here is the real fix:

https://alerts-v2.weather.gov/#/?id={}  # fill in the bit after the id

Check it out with this example:

**https://alerts-v2.weather.gov/#/?id=NWS-IDP-PROD-4245300-3580461**

You can thank me later... ;)

**Comment by jcla490** [comment]
nice find! I'll make the change. Not going to style off the json for now, too little time, lol
