### ISSUE TITLE
Clarify incident flow of information from WildCad -> EGP, etc.

### ISSUE THREAD

**Issue by kirk5davis** [washington-dnr-fire/wa-fire-dashboard#49]
Feedback from work doc:

- **Looking at the map it is not clear what date range of WildCad incidents you are viewing.  Currently it says incidents that are <24 hours are blue and >24 hours are purple.  Do incidents disappear after 48 hours or when entering patrol status, or is it until they are called out? I’m not sure what would be best, but it would be nice to know exactly what we are looking at.**  

My thoughts: If it does become a bigger incident, it would fall into our other fire category, we might want to adjust how these are label or explain it a bit more?  Thoughts?

**Comment by jcla490** [comment]
I changed the popups and legend to reflect this <24 and 24-48 hr stuff more clearly.
