### ISSUE TITLE
Add PLSS to map

### ISSUE THREAD

**Issue by kirk5davis** [washington-dnr-fire/wa-fire-dashboard#51]
From comments in Word doc:

- **Just that I would like be able to toggle PLSS on/off. **

Kind of easy to do, we can use an existing map service, but will need to configure a couple things:

- pop-up.

- zoom levels for section and township drawing

Here is the map service - technique in js will be identical to IFPL/Fire Danger, but will require two layers:
Sections: https://gis.dnr.wa.gov/site3/rest/services/Public_Boundaries/WADNR_PUBLIC_Cadastre_OpenData/MapServer/7

Townships:
https://gis.dnr.wa.gov/site3/rest/services/Public_Boundaries/WADNR_PUBLIC_Cadastre_OpenData/MapServer/8

**Comment by jcla490** [comment]
This is already available in the topographic layer in a different form.
