### ISSUE TITLE
Need to expose all data via api for chartjs functionality

### ISSUE THREAD

**Issue by jcla490** [washington-dnr-fire/wa-fire-dashboard#58]
ye

**Comment by kirk5davis** [comment]
base functionality has returned, but it only currently shows data for the "OverviewIntelReports".  Look at the view.py for current_fire_stats and you'll see how this is.  Feel free to change/update to include the region models (or data fields from them that you want).

Let me know what you're trying to display - there might be a better way to do this (i.e. we just pull straight from the EIRS data as json)
https://gis.dnr.wa.gov/site3/rest/services/Public_Wildfire/WADNR_PUBLIC_WD_WildFire_Data/MapServer/8/query?where=1%3D1&outFields=*&outSR=4326&f=json

**Comment by kirk5davis** [comment]
Try this query: 
https://gis.dnr.wa.gov/site3/rest/services/Public_Wildfire/WADNR_PUBLIC_WD_WildFire_Data/MapServer/2/query?where=START_DT+%3E+DATE+%272020-01-01%27&outSR=4326&outFields=*&returnGeometry=false&f=pjson

**Comment by kirk5davis** [comment]
This is the "WHERE" field: START_DT > DATE '2020-01-01'

**Comment by kirk5davis** [comment]
Querying Date Fields in Feature Services: https://www.esri.com/arcgis-blog/products/api-rest/data-management/querying-feature-services-date-time-queries/
